version: "3"

services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - "db"
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://user:password@db/db
      OFFERS_MS: ​https://applifting-python-excercise-ms.herokuapp.com/api/v1

  db:
    image: mysql:8.0
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_ROOT_HOST: '%'